PickPort/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from PickPort import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('items/', include('items.urls', namespace='items')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('success/', views.SuccessPage.as_view(), name='successful_login'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

categories/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from categories import views

app_name = 'categories'

urlpatterns = [
	path('list/', views.ListCategoryView.as_view(), name='list'),
	path('userlist/<int:pk>', views.UserListCategoryView.as_view(), name='userlist'),
	path('detail/<slug:slug>/', views.DetailCategoryView.as_view(), name='single'),
	path('create/', views.CreateCategoryView.as_view(), name='create'),
	path('update/<slug:slug>/', views.UpdateCategoryView.as_view(), name='update'),
	path('delete/<slug:slug>/', views.DeleteCategoryView.as_view(), name='delete'),
	path('search/', views.SearchCategoryView.as_view(), name='search'),
	path('subscribe/<slug:slug>/', views.SubCategoryView.as_view(), name='subscribe'),
	path('unsubscribe/<slug:slug>/', views.UnSubCategoryView.as_view(), name='unsubscribe'),
	path('like/<slug:slug>/', views.LikeCategoryView.as_view(), name='like'),
	path('unlike/<slug:slug>/', views.UnLikeCategoryView.as_view(), name='unlike'),
	path('sublist/<int:pk>', views.SubListCategoryView.as_view(), name='sublist'),
	path('contriblist/<int:pk>', views.RequestListContribView.as_view(), name='contriblist'),
	path('requestcontrib/<slug:slug>/', views.RequestContribView.as_view(), name='requestcontrib'),
	path('approvecontrib/<int:owner>/<int:pk>', views.ApproveContribView.as_view(), name='approvecontrib'),
	path('removecontrib/<int:owner>/<int:pk>', views.RemoveContribView.as_view(), name='removecontrib'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

items/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from items import views

app_name = 'items'

urlpatterns = [
	path('create/<int:pk>', views.CreateItem, name='create'),
	path('delete/<int:pk>', views.DeleteItem, name='delete'),
	path('update/<int:pk>', views.UpdateItem, name='update'),
	path('shuffle/<int:pk>', views.ShuffleItem, name='shuffle'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'PickPort/css/navbar.css'%}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/gh/mathusummut/confetti.js/confetti.min.js"></script>

</head>
<body>
	
	<nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #000;">
		<a class="navbar-brand textWhite" href="{% url 'index' %}">PickPort</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#restOfNavbar" aria-controls="restOfNavbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse justify-content-between align-items-center" id="restOfNavbar">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle textWhite navLink" href="#" id="CategoryDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
					
					<div class="dropdown-menu" aria-labelledby="CategoryDropdown">
						<a class="dropdown-item" href="{% url 'categories:list' %}">All Categories</a>

						{% if user.is_authenticated %}
							<a class="dropdown-item" href="{% url 'categories:userlist' pk=request.user.id %}">My Categories</a>
							<a class="dropdown-item" href="{% url 'categories:create' %}">New Category</a>
						{% endif %}
					</div>
				</li>
				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link navLink" href="{% url 'categories:sublist' pk=request.user.id %}">Subscriptions</a>
					</li>
					<li class="nav-item">
						<a class="nav-link navLink" href="{% url 'categories:contriblist' pk=request.user.id %}">Requests</a>
					</li>
				{% endif %}
			</ul>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link navLink" href="{% url 'admin:index' %}">Admin</a>
				</li>
				<li class="nav-item">
					<a class="nav-link navLink" href="{% url 'accounts:signup' %}">Sign Up</a>
				</li>
				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link navLink" href="{% url 'accounts:logout' %}">Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link navLink" href="{% url 'accounts:login' %}">Login</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	



	<!--<nav class="header">
		<ul class="menu">
			<li class="logo">
				<a href="{% url 'index' %}">PICKPORT</a>
			</li>
			<li class="item dropdown">
				<a href="#">Categories</a>
				<ul>
					<li>
						<a href="{% url 'categories:list' %}">All Categories</a>	
					</li>
					{% if user.is_authenticated %}
						<li>
							<a href="{% url 'categories:userlist' pk=request.user.id %}">My Categories</a>
						</li>
						<li>
							<a href="{% url 'categories:create' %}">New Category</a>	
						</li>
					{% endif %}
				</ul>
			</li>
			{% if user.is_authenticated %}
			<li class="item">
				<a href="{% url 'categories:sublist' pk=request.user.id %}">Subscriptions</a>
			</li>
			<li class="item">
				<a href="{% url 'categories:contriblist' pk=request.user.id %}">Requests</a>	
			</li>
			{% endif %}
			<li class="item">
				<a href="{% url 'admin:index' %}">Admin</a>	
			</li>		
			{% if user.is_authenticated %}
				<li class="item button">
					<a href="{% url 'accounts:logout' %}">Logout</a>	
				</li>
			{% else %}
				<li class="item button">
					<a href="{% url 'accounts:login' %}">Login</a>	
				</li>
			{% endif %}
			<li class="item button secondary">
				<a href="{% url 'accounts:signup' %}">Sign Up</a>	
			</li>
			<li class="toogle">
				<span class="bars"></span>
			</li>
		</ul>
	</nav>-->

	<!--<div class="nav-container">
		<nav>
			<div class="left-menu">
				<ul>
					<li>
						<a href="#">Categories</a>
						<ul class="dropdown">
							<li class="dropdown-element">
								<a href="{% url 'categories:list' %}">All Categories</a>	
							</li>
							{% if user.is_authenticated %}
								<li class="dropdown-element">
									<a href="{% url 'categories:userlist' pk=request.user.id %}">My Categories</a>
								</li>
								<li class="dropdown-element">
									<a href="{% url 'categories:create' %}">New Category</a>	
								</li>
							{% endif %}
						</ul>
					</li>
					{% if user.is_authenticated %}
					<li>
						<a href="{% url 'categories:sublist' pk=request.user.id %}">Subscriptions</a>
					</li>
					<li>
						<a href="{% url 'categories:contriblist' pk=request.user.id %}">Requests</a>	
					</li>
					{% endif %}
				</ul>
			</div>
			<a class="logo" href="{% url 'index' %}">PICKPORT</a>
			<div class="right-menu">
				<ul>
					<li>
						<a href="{% url 'admin:index' %}">Admin</a>	
					</li>
					<li>
						<a href="{% url 'accounts:signup' %}">Sign Up</a>	
					</li>			
					{% if user.is_authenticated %}
						<li>
							<a href="{% url 'accounts:logout' %}">Logout</a>	
						</li>
					{% else %}
						<li>
							<a href="{% url 'accounts:login' %}">Login</a>	
						</li>
					{% endif %}
				</ul>
			</div>
		</nav>
	</div>-->
	<!--
	<header>
		<ul>
			<li>
				<a href="#">Categories</a>
				<ul>
					<li>
						<a href="{% url 'categories:list' %}">All Categories</a>
					</li>
					{% if user.is_authenticated %}
						<li>
							<a href="{% url 'categories:userlist' pk=request.user.id %}">My Categories</a>
						</li>
						<li>
							<a href="{% url 'categories:create' %}">New Category</a>	
						</li>
					{% endif %}
				</ul>
			</li>
			{% if user.is_authenticated %}
				<li>
					<a href="{% url 'categories:sublist' pk=request.user.id %}">Subscriptions</a>
				</li>
				<li>
					<a href="{% url 'categories:contriblist' pk=request.user.id %}">Requests</a>	
				</li>
			{% endif %}
			<li>
				<a href="{% url 'index' %}">PICKPORT</a>
			</li>
			<li>
				<a href="{% url 'admin:index' %}">Admin</a>
			</li>
			<li>
				<a href="{% url 'accounts:signup' %}">Sign Up</a>	
			</li>			
			{% if user.is_authenticated %}
				<li>
					<a href="{% url 'accounts:logout' %}">Logout</a>	
				</li>
			{% else %}
				<li>
					<a href="{% url 'accounts:login' %}">Login</a>	
				</li>
			{% endif %}
		</ul>
	</header>-->

	
	{% block content %}

	{% endblock %}
	
	<footer>
		<a href="#">@Copyright - PickPort</a>
		<a href="#"> Imprint</a>
		<a href="#">Contact</a>
	</footer>

	<script src="{% static 'PickPort/js/toogle.js' %}" type="text/javascript"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
	{% load static %}
	{% block content %}
		<div class="backgroundImage"></div>
		<div class="container containerTop">
			<section class="welcomeSection">
				<div class="welcomeBox">
					<h1 class="headlineOne">Simplest way to make choices</h1>
					<h2 class="headlineTwo">No stress</h2>
					<h2 class="headlineThree">No hustle</h2>
					<a class="btn btn-primary btnPosition" href="{% url 'categories:list' %}">Start Now</a>	
				</div>
			</section>
		</div>


		
	{% endblock %}

templates/successful_login.html
{% extends "base.html" %}
	{% block content %}
		<div align="center">
			<h1>You have logged in successfully.</h1>
			<h2><a href="{% url 'categories:list' %}">If you want to see all the categories, please click here.</a></h2>	
		</div>
	{% endblock %}

templates/thanks.html
{% extends "base.html" %}
	{% block content %}
		<div align="center">
			<h1>Please come back soon!</h1>	
		</div>
	{% endblock%}