PickPort/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from PickPort import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('items/', include('items.urls', namespace='items')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('success/', views.SuccessPage.as_view(), name='successful_login'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

categories/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from categories import views

app_name = 'categories'

urlpatterns = [
	path('list/', views.ListCategoryView.as_view(), name='list'),
	path('userlist/<int:pk>', views.UserListCategoryView.as_view(), name='userlist'),
	path('detail/<slug:slug>/', views.DetailCategoryView.as_view(), name='single'),
	path('create/', views.CreateCategoryView.as_view(), name='create'),
	path('update/<slug:slug>/', views.UpdateCategoryView.as_view(), name='update'),
	path('delete/<slug:slug>/', views.DeleteCategoryView.as_view(), name='delete'),
	path('search/', views.SearchCategoryView.as_view(), name='search'),
	path('subscribe/<slug:slug>/', views.SubCategoryView.as_view(), name='subscribe'),
	path('unsubscribe/<slug:slug>/', views.UnSubCategoryView.as_view(), name='unsubscribe'),
	path('like/<slug:slug>/', views.LikeCategoryView.as_view(), name='like'),
	path('unlike/<slug:slug>/', views.UnLikeCategoryView.as_view(), name='unlike'),
	path('sublist/<int:pk>', views.SubListCategoryView.as_view(), name='sublist'),
	path('contriblist/<int:pk>', views.RequestListContribView.as_view(), name='contriblist'),
	path('requestcontrib/<slug:slug>/', views.RequestContribView.as_view(), name='requestcontrib'),
	path('approvecontrib/<int:owner>/<int:pk>', views.ApproveContribView.as_view(), name='approvecontrib'),
	path('removecontrib/<int:owner>/<int:pk>', views.RemoveContribView.as_view(), name='removecontrib'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

items/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from items import views

app_name = 'items'

urlpatterns = [
	path('create/<int:pk>', views.CreateItem, name='create'),
	path('delete/<int:pk>', views.DeleteItem, name='delete'),
	path('update/<int:pk>', views.UpdateItem, name='update'),
	path('shuffle/<int:pk>', views.ShuffleItem, name='shuffle'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

categories/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=255, unique=True)
	description = models.TextField(blank=True, default='')
	slug = models.SlugField(allow_unicode=True, unique=True)
	created_date = models.DateTimeField(default=timezone.now)
	user = models.ForeignKey(User, default=999, related_name='user_categories', on_delete= models.CASCADE)
	subscribers = models.ManyToManyField(User, related_name= 'subscribers',through='CategorySubscriber')
	likes = models.ManyToManyField(User,related_name='likes', through='CategoryLike')
	contributors = models.ManyToManyField(User, related_name='contributors', through='CategoryContributor')
	
	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('categories:userlist', kwargs={'pk': self.user.id})

class CategorySubscriber(models.Model):
	user = models.ForeignKey(User, related_name='user_subs', on_delete=models.CASCADE)
	category = models.ForeignKey(Category, related_name='subs', on_delete=models.CASCADE)
	sub_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.user.first_name

	class Meta:
		unique_together = ("user", "category")

class CategoryLike(models.Model):
	user = models.ForeignKey(User, related_name='user_likes', on_delete=models.CASCADE)
	category = models.ForeignKey(Category, related_name='category_likes', on_delete=models.CASCADE)

	def __str_(self):
		return self.user.username

	class Meta:
		unique_together = ('user', 'category')

class CategoryContributor(models.Model):
	user = models.ForeignKey(User, related_name='user_contrib', on_delete=models.CASCADE)
	category = models.ForeignKey(Category, related_name='contribs', on_delete=models.CASCADE)
	approved =models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

	class Meta:
		unique_together = ('user', 'category')

categories/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from braces.views import SelectRelatedMixin

from django.views import generic, View
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()

from categories.models import Category, CategorySubscriber, CategoryLike, CategoryContributor
from items.models import Items

# Create your views here.

class CreateCategoryView(LoginRequiredMixin, generic.edit.CreateView):
	fields = ('name', 'description')
	model = Category

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.save()

		return super().form_valid(form)

class ListCategoryView(generic.ListView):
	model = Category
	

	def get_context_data(self, **kwargs):
		latest = Category.objects.order_by('-created_date')[:5]
		most_likes = Category.objects.annotate(num_likes = Count('likes')).order_by('-num_likes')[:5]
		context = super().get_context_data(**kwargs)
		context['latest_cat'] = latest
		context['most_likes'] = most_likes

		return context


class UserListCategoryView(LoginRequiredMixin, generic.ListView):
	model = Category
	template_name = 'categories/category_user_list.html'

	def get_queryset(self):
		#Processing the queryset
		queryset = super().get_queryset()
		return queryset.filter(user_id=self.request.user.id)

class SubListCategoryView(LoginRequiredMixin, generic.ListView):
	model = Category
	template_name = 'categories/category_sub_list.html'
	context_object_name = 'category_sub_list'

	def get_queryset(self):
		queryset = super().get_queryset()

		return queryset.filter(subscribers=self.request.user.id)

class DetailCategoryView(LoginRequiredMixin, generic.DetailView):
	model = Category


class UpdateCategoryView(LoginRequiredMixin, generic.edit.UpdateView):
	model = Category
	fields = ['name', 'description']
	template_name_suffix = '_update_form'

	def get_success_url(self):
		return reverse_lazy('categories:userlist', kwargs={'pk': self.request.user.id})

class DeleteCategoryView(LoginRequiredMixin, generic.edit.DeleteView):
	model = Category
	
	def get_success_url(self):
		return reverse_lazy('categories:userlist', kwargs={'pk': self.request.user.id})

class SearchCategoryView(View):
	template_name = 'categories/category_search_results.html'

	def get_queryset(self):
		queryset = Category.objects.order_by('name')
		
		return queryset

	def post(self, request):
		cats = self.get_queryset()
		result = cats.filter(name__contains=request.POST['search_name'])

		return render(request, self.template_name, {'result': result})


class SubCategoryView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('categories:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		cat = get_object_or_404(Category, slug=self.kwargs.get('slug'))

		try:
			CategorySubscriber.objects.create(user=self.request.user, category=cat)

		except IntegrityError:
			messages.warning(self.request, "Warning, already subscriber of {} category".format(cat.name))

		else:
			messages.success(self.request, "You are successfully subscribed to the {} category".format(cat.name))

		return super().get(request, *args, **kwargs)

class UnSubCategoryView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('categories:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		try:
			sub = CategorySubscriber.objects.filter(user=self.request.user, category__slug=self.kwargs.get('slug')).get()

		except CategorySubscriber.DoesNotExist:
			messages.warning(self.request, "You aren`t even a subscriber")

		else:
			sub.delete()
			messages.success(self.request, 'You successfully unsubscribed to')

		return super().get(request, *args, **kwargs)

class LikeCategoryView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('categories:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		cat = get_object_or_404(Category, slug=self.kwargs.get('slug'))

		try:
			CategoryLike.objects.create(user=self.request.user, category=cat)

		except IntegrityError:

			messages.warning(self.request, 'You already liked this category')

		else:

			messages.success(self.request, 'You liked this category')

		return super().get(request, *args, **kwargs)


class UnLikeCategoryView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('categories:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		try:
			like = CategoryLike.objects.filter(user= self.request.user, category__slug=self.kwargs.get('slug')).get()

		except CategoryLike.DoesNotExist:

			messages.warning(self.request, 'You didn`t even liked the category')

		else:
			like.delete()
			messages.success(self.request, 'You removed your like now')

		return super().get(request, *args, **kwargs)

class RequestContribView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('categories:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):
		cat = get_object_or_404(Category, slug=self.kwargs.get('slug'))

		try:
			CategoryContributor.objects.create(user=self.request.user, category=cat)

		except IntegrityError:

			messages.warning(self.request, "You already ask to be a contributor")

		else:

			messages.success(self.request, 'You successfully requested to be a contributor')

		return super().get(request, *args, **kwargs)

class RequestListContribView(LoginRequiredMixin, generic.ListView):
	model = Category
	template_name = 'categories/category_requested_contrib.html'
	context_object_name = 'requested_contribs'

	def get_queryset(self):
		queryset = super().get_queryset()
		current_user_cats = queryset.filter(user = self.request.user.id)
		usr = User.objects.filter(id__in=current_user_cats.values_list('contributors', flat=True))
		
		usr_status_dict = {}

		for u in usr:

			usr_status_dict[u] = u.user_contrib.values_list('approved', flat=True)[0]

		return usr_status_dict

class ApproveContribView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, **kwargs):
		return reverse('categories:contriblist', kwargs={'pk': self.kwargs.get('owner')})

	def get(self, request, *args, **kwargs):

		contrib_usr = get_object_or_404(CategoryContributor, user=self.kwargs.get('pk'))

		if contrib_usr.approved == False:
			contrib_usr.approved = True
			contrib_usr.save()
			messages.success(self.request, "Successfully approved")

		else:
			messages.warning(self.request, "You already approved this request")			


		return super().get(request, *args, **kwargs)

class RemoveContribView(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, **kwargs):
		return reverse('categories:contriblist', kwargs={'pk': self.kwargs.get('owner')})

	def get(self, request, *args, **kwargs):

		contrib_usr = get_object_or_404(CategoryContributor, user=self.kwargs.get('pk'))

		if True:
			contrib_usr.delete()
			messages.success(self.request, 'Successfully declined')
			
		elif contrib_usr.DoesNotExist:
			messages.warning(self.request, 'You already declined the request')
			

		return super().get(request, *args, **kwargs)


class TestView(generic.ListView):
	model= CategoryLike

categories/templates/categories/category_base.html
{% extends "base.html" %}
	{% block content %}
		<div class="container topSpace bottomSpace">
			<div class="row">
				{% block pre_category %}{% endblock %}
				{% block main_category %}{% endblock %}
				{% block post_category %}{% endblock %}
			</div>
		</div>
		
		
	{% endblock %}

categories/templates/categories/category_confirm_delete.html
{% extends "categories/category_base.html" %}
	{% block main_category %}
		
			<div class="col-sm-12 align-self-center" align="center">
				<div class="card cardShape cardSize">
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}
								<h5 class="card-text">If you confirm the delete, the category will be gone. Do you want to continue?</h5>
								<input type="submit" class="btn btn-danger" value="Confirm">
								<a href="{% url 'categories:userlist' pk=request.user.id %}" class="btn btn-secondary">Cancel</a>
						</form>
					</div>
				</div>
			</div>
			
		
	{% endblock %}

categories/templates/categories/category_detail.html
{% extends "categories/category_base.html" %}
	{% block main_category %}
		{% if category.user != request.user %}
			<div id="mySideAction" class="sideAction">
				{% if user in category.subscribers.all %}
					<a class="unsubscribe" href="{% url 'categories:unsubscribe' slug=category.slug %}">Unsubscribe <span class="material-icons sizeIconInButton">remove_circle_outline</span></a>
				{% else %}
					<a class="subscribe" href="{% url 'categories:subscribe' slug=category.slug %}">Subscribe <span class="material-icons sizeIconInButton">check_circle_outline</span></a>
				{% endif %}

				{% if user in category.likes.all %}
					<a class="unlike" href="{% url 'categories:unlike' slug=category.slug %}">Unlike <span class="material-icons favColorFull">favorite</span></a>
				{% else %}
					<a class="like" href="{% url 'categories:like' slug=category.slug %}">Like <span class="material-icons favColorFull">favorite_border</span></a>
				{% endif %}
				<a class="contribution" href="{% url 'categories:requestcontrib' slug=category.slug %}">Contributor <span class="material-icons">group_add</span></a>
			</div>
		{% endif %}

		<div class=container>
			<div class="row">
				<div class="col-sm-12">
					<h2 class="bottomSpace" align="center">Here you will find a list of all items with regards to category: {{ category.name }}</h2>
					<div class="card cardShape cardSize">
						<div class="card-body">
							{% if category.items.count == 0 %}
								<h4 align="center">Currently there are no items related to this category</h4>
								{% if category.user == request.user %}
									<p align="center">You can add one by clicking the button</p>
								{% else %}
									<p align="center">The creator will soon add items to this category</p>
								{% endif %}
							{% else %}
								<table class="table table-hover table-bordered mb-0">
									<thead class="bg-primary textWhite">
										<th>#</th>
										<th>Item Name</th>
										<th>Creation Date</th>
										{% if category.user == request.user %}
											<th>Action</th>
										{% endif %}
									</thead>
									<tbody>
										{% for item in category.items.all %}
											<tr>
												<td>{{ forloop.counter }}</td>
												<td>{{ item.name }}</td>
												<td>{{ item.created_date }}</td>
												{% if category.user == request.user %}
													<td>
														<a href="{% url 'items:update' pk=item.pk %}" class="btn btn-warning"><span class="material-icons" style="color: white">edit</span></a>
														<a href="{% url 'items:delete' pk=item.pk %}" class="btn btn-danger"><span class="material-icons">delete_forever</span></a>
													</td>
												{% endif %}
											</tr>
										{% endfor %}
									</tbody>
								</table><br>
							{% endif %}

							{% if user.is_authenticated %}
								{% if category.user == request.user%}
									{% if category.items.count == 0 %}
										<div class="btnCenter">
											<a href="{% url 'items:create' pk=category.pk %}" class="btn btn-primary">Create Item</a>
										</div>
									{% else %}
										<a href="{% url 'items:create' pk=category.pk %}" class="btn btn-primary">Create Item</a>
									{% endif %}
								{% endif %}
							{% endif %}
							
							{% if category.items.count != 0 %}
								<hr class="mt-3 mb-3">
								<form method="POST" action="{% url 'items:shuffle' pk=category.pk %}">
									{% csrf_token %}
									<div class="form-group">
										<label>How many elements do you want to shuffle?</label>
										<select class="form-control" name="number">
											{% for item in category.items.all %}
												<option>{{ forloop.counter }}</option>
											{% endfor %}
										</select>
									</div>
									<input type="submit" value="Shuffle" class="btn btn-success">
								</form>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		
	{% endblock %}

categories/templates/categories/category_form.html
{% extends "categories/category_base.html" %}
	{% load crispy_forms_tags %}
		{%block main_category %}
			<div class="container">
				<h3 class="bottomSpace" align="center">Please enter a name and description of the category you wanna create</h3>
				<div class="card cardShape cardSize">
					<div class="card-body">
						<form class="bootstrap4" method="POST" action="{% url 'categories:create' %}">
							{% csrf_token %}
							{{ form|crispy }}
							<input type="submit" class="btn btn-primary" value="Create">
							<a href="{% url 'categories:userlist' pk=request.user.id %}" class="btn btn-secondary">Cancel</a>
						</form>

					</div>
				</div>
			</div>
				
		{% endblock %}

categories/templates/categories/category_list.html
{% extends "categories/category_base.html" %}
	{% block pre_category %}
		<div class="col-md-2">
			<div class="content">				
				<h1>Groups</h1>
				<p>Here you will find an overview of the current categories:</p>	
			</div>
		</div>
	{% endblock %}

	{% block main_category %}
		<div class="col-md-7">
			<div class="row row-cols-1 row-cols-md-3">
			  	{% for category in object_list %}
				  <div class="col mb-4">
				    <div class="card cardShape text-dark bg-light mb-3 h-100">
				      <div class="card-header bg-secondary d-flex justify-content-between">
				      	<h5 class="card-title"><a class="categoryItems" href="{% url 'categories:single' slug=category.slug %}">{{ category.name }}</a></h5>
				      	<small><span class="badge badge-warning likesIcon" style="font-size: large;"><span class="material-icons favColorFull sizeIcon">favorite</span> {{ category.likes.count }}</span></small>
				      </div>
				      <div class="card-body">
				        <p class="card-text">{{ category.description }}</p>
				      </div>
				    </div>
				  </div>
				{% endfor %}
			</div>
		</div>
	{% endblock %}

	{% block post_category %}
		<div class="col-md-3">
			<div class="card cardShape">
				<header>
			        <h6 class="mt-4 ml-3">Search for categories</h6>
			    </header>
			    <form method="POST" action="{% url 'categories:search' %}">
			    	{% csrf_token %}
				  	<div class="input-group mb-3 ml-3 inputShape">
				  		<input class="form-control" type="text" name="search_name" placeholder="Search" aria-label="Search">
				  		<div class="input-group-append">
				  			<button class="btn btn-outline-primary" type="submit"><span class="material-icons" style="font-size: 95%" >search</span></button>
				  		</div>
				  	</div>
				</form>
			</div>
			<div class="card cardShape mt-3">
				<header>
					<h6 class="mt-4 ml-3">Latest created categories</h6>
				</header>
				{% for cat in latest_cat %}
					<a href="{% url 'categories:single' slug=cat.slug%}" class="btn btn-outline-info buttonSize">{{ cat.name }}</a><br>
				{% endfor %}
			</div>
			<div class="card cardShape mt-3">
				<header>
					<h6 class="mt-4 ml-3">Most Likes</h6>
				</header>
				
					{% for cats in most_likes %}
					<div class="d-flex justify-content-between mt-4 ml-3 mr-3 mb-2">
						<a class="likeItems" href="{% url 'categories:single' slug=cats.slug %}">{{cats.name}}</a>
						<small><span class="badge badge-warning likesIcon" style="font-size: large;"><span class="material-icons favColorFull sizeIcon">favorite</span> {{ cats.likes.count }}</span></small>
					</div>
					{% endfor %}
				
			</div>
		</div>
						
	{% endblock %}

categories/templates/categories/category_requested_contrib.html
{% extends 'categories/category_base.html' %}
	{% block main_category %}
		{% if requested_contribs|length == 0 %}
			<div class="col-md-12 align-self-center">
				<div class="card cardShape cardSize">
					<div class="card-body">
						<h3 align="center">Currently no one wants to contribute to your categories</h3>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-md-12 align-self-center">
				<div class="card cardShape">
					<div class="card-header bg-secondary text-white">
						<h4 align="center">Those users would like to contribute to your categories</h4>
					</div>
					<div class="card-body">
						<table class="table table-hover table-bordered mb-0">
							<thead class="text-white bg-primary">
								<th>#</th>
								<th>Username</th>
								<th>Status</th>
								<th>Action</th>
							</thead>
							<tbody>
								{% for key, value in requested_contribs.items %}
									<tr>
										<td>{{forloop.counter}}</td>
										<td>{{key.username}}</td>
										<td>
											{% if value is False %}
												Not approved yet
											{% elif value is True %}
												Already approved
											{% endif %}
										</td>
										<td>
											<a href="{% url 'categories:approvecontrib' owner=user.id pk=key.pk %}" class="btn btn-success"><span class="material-icons">thumb_up_alt</span></a>
											<a href="{% url 'categories:removecontrib' owner=user.id pk=key.pk %}" class="btn btn-danger"><span class="material-icons">thumb_down_alt</span></a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		{% endif %}	
		
	{% endblock %}

categories/templates/categories/category_search_results.html
{% extends "categories/category_base.html" %}
	{% block pre_category %}
		<div class="col-md-2">
			<div class="content">				
				<h1>Groups</h1>
				<p>Here are the categories you have searched for:</p>
			</div>
			<a href="{% url 'categories:list' %}" class="btn btn-primary"><span class="material-icons" style="font-size: 95%">arrow_back</span> Go back</a>
		</div>
	{% endblock %}

	{% block main_category %}
		<div class="col-md-7">
			<div class="row row-cols-1 row-cols-md-3">
			  	{% for re in result %}
				  <div class="col mb-4">
				    <div class="card card-1 text-white bg-secondary mb-3 h-100">
				      <!--<img src="..." class="card-img-top" alt="...">-->
				      <div class="card-body">
				        <h5 class="card-title"><a class="categoryItems" href="{% url 'categories:single' slug=re.slug %}">{{ re.name }}</a></h5>
				        <p class="card-text">{{ re.description }}</p>
				      </div>
				    </div>
				  </div>
				{% endfor %}
			</div>
		</div>
	{% endblock %}

categories/templates/categories/category_sub_list.html
{% extends 'categories/category_base.html' %}
	{% block pre_category %}
		{% if category_sub_list.count != 0 %}
			<div class="col-md-4">
				<div class="content">
					<h3>Hey {{ user.username }}</h3>
					<h4>Here is a list of all your subscriptions</h4>
				</div>
			</div>
		{% endif %}
	{% endblock %}

	{% block main_category %}
		{% if category_sub_list.count != 0 %}
			<div class="col-md-8">
				<div class="row row-cols-1 row-cols-md-3">
					{% if category_sub_list.count == 0 %}
						<p>The list is empty</p>
					{% else %}
					  	{% for category in category_sub_list %}
						  <div class="col mb-4">
						    <div class="card cardShape text-dark bg-light mb-3 h-100">
						      <div class="card-header bg-secondary d-flex justify-content-between">
						      	<h5 class="card-title"><a class="categoryItems" href="{% url 'categories:single' slug=category.slug %}">{{ category.name }}</a></h5>
						      	<small><span class="badge badge-warning likesIcon" style="font-size: large;"><span class="material-icons favColorFull sizeIcon">favorite</span> {{ category.likes.count }}</span></small>
						      </div>
						      <div class="card-body">
						        <p class="card-text">{{ category.description }}</p>
						      </div>
						    </div>
						  </div>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		{% else %}
			<div class="col-md-12">
				<h3 align="center">Hey {{ user.username }}</h3>
				<h4 align="center">Looks like you haven`t subscribed to any category yet</h4>
			</div>
		{% endif %}
	{% endblock %}

categories/templates/categories/category_update_form.html
{% extends "categories/category_base.html" %}
	{% load crispy_forms_tags %}
		{%block main_category %}
			<div class="container">
				<h3 class="bottomSpace" align="center">You can enter your changes here</h3>
				<div class="card cardShape cardSize">
					<div class="card-body">
						<form class="bootstrap4" method="POST" action="{% url 'categories:update' slug=category.slug%}">
							{% csrf_token %}
							{{ form|crispy }}
							<input type="submit" class="btn btn-warning" value="Update">
							<a href="{% url 'categories:userlist' pk=request.user.id%}" class="btn btn-secondary">Cancel</a>
						</form>
					</div>
				</div>
			</div>
		{% endblock %}

categories/templates/categories/category_user_list.html
{% extends 'categories/category_base.html' %}
	{% block pre_category %}
	{% if object_list.count == 0 %}
		<div class="col-md-12">
			<div class="card cardShape cardWelcome">
				<div class="content">
					<h1 class="welcomeBack">Welcome back @{{user.username}}</h1>
					<h5>It looks like you haven't created a category yet. Just start now</h5>
				</div>

				{% if user.is_authenticated %}
					<a href="{% url 'categories:create' %}" class="btn btn-primary btnCreate">Create Category</a>
					
				{% endif %}
			</div>
		</div>
	{% else %}
		<div class="col-md-4">
			<div class="content">
				{% if user.is_authenticated %}
					<h1>Welcome back @{{user.username}}</h1>
				{% else %}
					<h1>Groups</h1>
					<p>Here you will find an overview of the current categories:</p>
				{% endif %}
			</div>

			{% if user.is_authenticated %}
				<a href="{% url 'categories:create' %}" class="btn btn-primary">Create Category</a>
				
			{% endif %}
		</div>
	{% endif %}
	{% endblock %}

	{% block main_category %}
	{% if object_list.count > 0 %}
		<div class="col-md-8">
			<div class="row row-cols-1 row-cols-md-3">
			  	{% for category in object_list %}
				  <div class="col mb-4">
				    <div class="card cardShape text-dark bg-light mb-3 h-100">
				      <div class="card-header bg-secondary d-flex justify-content-between">
				      	<h5 class="card-title"><a class="categoryItems" href="{% url 'categories:single' slug=category.slug %}">{{ category.name }}</a></h5>
				      	<small><span class="badge badge-warning likesIcon" style="font-size: large;"><span class="material-icons favColorFull sizeIcon">favorite</span> {{ category.likes.count }}</span></small>
				      </div>
				      <div class="card-body">
				        <p class="card-text">{{ category.description }}</p>
				      </div>
				      <div class="card-footer bg-secondary d-flex justify-content-between">
				        	{% if user.is_authenticated %}
					        	<a href="{% url 'categories:update' slug=category.slug %}" class="btn btn-warning">Update</a>
					        	<a href="{% url 'categories:delete' slug=category.slug %}" class="btn btn-danger">Delete</a>
					        {% endif %}
				        </div>
				    </div>
				  </div>
				{% endfor %}
			</div>
		</div>
	{% endif %}
	{% endblock %}